# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ciclodevida' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ciclodevida
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'GoogleSignIn', '~> 4.0.2'

end

target 'ciclodevida-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ciclodevida-tvOS

  target 'ciclodevida-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
